server:
  port: 8081
  host: localhost
profile:
  active: dev


database:
  host: localhost
  user: postgres
  password: postgrespassword
  dbname: postgres
  sslmode: disable
  timezone: UTC
  port: 5432


sessionDeleteScheduler: "@every 1h"

password:
  resetExpire: 24
  minLength: 5
  forgotPasswordTokenExpire: 1440
  activateAccountTokenExpire: 1440
  jwt:
    secretKey: secret
    publicKey: secret
    privateKey: secret
    saltKey: secret
    accessTokenExpire: 3
    refreshTokenExpire: 5


redis:
  host: localhost
  port: 6379
  db: 1
  expires: 1000


mail:
  username: frasulov1309@gmail.com
  password: F5566041f
  host: smtp.gmail.com
